### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by mr-church** [mttgdd/openfabmap-python3#1]
Hi Matt, 
I am trying to build this with OpenCV 3.4. I have cloned and built openCV 3.4 as well as opencv-contrib 3.4 

There are a few issues building the repo: 
1. The sub-modules did not clone correctly. I had to manually clone them into the respective folders in your repo. I think there was an issue with how they are called. I also had to clone your repo itself, the terminal inputs in the readme.md threw up public key errors it also seems like the name of the repo changed? openfabmap-python to openfabmap-python3? 

2. Not using opencv built from the package installer [i.e sudo apt install libopencv-dev] results in line 3 of detectorsAndExtractors.cpp needing to be changed to point to nonfree.hpp in the contrib module [though this workaround never really worked on either repo so I have a suspicion that there is something amiss] 

The complie then fails with the following error: 

> CMakeFiles/openfabmap_python3.dir/build.make:206: recipe for target 'CMakeFiles/openfabmap_python3.dir/src/detectorsAndExtractors.cpp.o' failed
make[2]: *** [CMakeFiles/openfabmap_python3.dir/src/detectorsAndExtractors.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openfabmap_python3.dir/all' failed
make[1]: *** [CMakeFiles/openfabmap_python3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

So I think there is something wrong here. Though when running just the cmake file of openFABMAP it finds openCV 3.4.14 and the non-free modules. 

I have also have a dump of the whole terminal so that you can see that commands used, if this will help you. 

I hope this makes sense to you. 

Matt

**Comment by mr-church** [comment]
These are the steps I followed to install OpenCV 

https://learnopencv.com/install-opencv-3-4-4-on-ubuntu-18-04/

**Comment by mttgdd** [comment]
I have resolved the sub-module clone by updating the README:
```bash
git clone --recurse-submodules git@github.com:mttgdd/openfabmap-python3.git src
```

**Comment by mttgdd** [comment]
@mr-church could you let me know which Ubuntu version you are using? Or which other operating system?

**Comment by mttgdd** [comment]
@mr-church , I have compiled a docker images from Ubuntu 16.04 with Python 3.6 and OpenCV non-free
https://hub.docker.com/r/matthewgadd/openfabmap-python3
While doing so, I fixed a couple of errors, so this should probably compile for you.
I will close this issue now as it started with a family of issues, but please do open a new one with specific problems if they still persist :)
