### ISSUE TITLE
example, seg-fault

### ISSUE THREAD

**Issue by mttgdd** [mttgdd/openfabmap-python3#2]
Hi @mr-church, could you confirm that on a fresh pull of the docker image/clone of the repo/however you have it installed, that you now pass through this point in the example without seg-faulting:

```bash
use OpenCV cpp methods for image loading and feature extraction
```

My apologies for the error, it must have crept in when I was making changes to the API elsewhere. Just needed to pass explicit settings for OpenCV detector-extractors.

**Comment by mr-church** [comment]
Hi @mttgdd, I have been attempting to use the docker image as a local install is plagued with version issues. 
I still get the segmentation fault on the docker image and when I try to import cv2 into the python3 it says there is no cv2 module. 

![Screenshot from 2021-06-16 12-34-59](https://user-images.githubusercontent.com/74924868/122205045-1659b880-cea0-11eb-8e36-a174712f531c.png)

Running GDB I get the following: 

![Screenshot from 2021-06-16 12-41-34](https://user-images.githubusercontent.com/74924868/122205161-39846800-cea0-11eb-880e-f8bb9fb45c27.png)

**Comment by mttgdd** [comment]
I am sorry! I think I didn't reflect the github changes in the docker image. I have now done so, if you pull the latest docker build, it should run the example without any issue

**Comment by mttgdd** [comment]
Also you can just use the command `python` instead of `python3` in the docker

**Comment by mr-church** [comment]
> I am sorry! I think I didn't reflect the github changes in the docker image. I have now done so, if you pull the latest docker build, it should run the example without any issue

Hi @mttgdd, yes the docker image works well now. 
Apologies for not getting back to you sooner. This issue can be closed now.
